services:
  - type: pserv
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: ohio
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set this in the Render dashboard
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: aact

  - type: web
    name: clinical-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    region: ohio
    plan: free
